### ISSUE TITLE
Add automile-php to packagist

### ISSUE THREAD

**Issue by uberswe** [Automile/automile-php#1]
Can we publish this on packagist https://packagist.org/

Currently I am unable to find the project via composer 
<img width="1107" alt="e9c9d7fd8fa2399efe980be1fed7e0ae" src="https://cloud.githubusercontent.com/assets/1903284/23657746/fadcb984-033f-11e7-8b6c-b14ea6a7af3a.png">

**Comment by sergeymitr** [comment]
@markustenghamn that's the plan, I'm waiting for the Packagist account credentials

**Comment by jensnylander** [comment]
@markustenghamn We have now added the package to packagist. The current version is a pre-release but all major endpoints and methods are supported.

**Comment by uberswe** [comment]
Awesome!
